name: Editorconfig

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  editorconfig:
    name: Lint

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Set Up NodeJS
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: lts/*

      - name: Install Dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run editorconfig:lint
